# Uncomment the next line to define a global platform for your project
 platform :ios, ‘8.0’

target 'RAC+MVVM' do
   use_frameworks!
pod ‘ReactiveObjC’
pod ‘AFNetworking’
pod ‘MJExtension’
pod ‘SDWebImage’

end
